### ISSUE TITLE
Upstart services fail to start zookeeper

### ISSUE THREAD

**Issue by DarrenV79** [evertrue/zookeeper-cookbook#179]
Upstart gives the error 'start-stop-daemon: unable to stat /bin/java (No such file or directory)'.  It appears the JAVA_HOME value is not valid at the time upstart starts.

This is on Ubuntu 14.04.

**Comment by jeffbyrnes** [comment]
@DarrenV79 would you describe your situation more fully? I’m unable to reproduce this with the test suite.

**Comment by jeffbyrnes** [comment]
Oh, wait, yes I am. Derp. Fixing!

**Comment by DarrenV79** [comment]
Hi,

I modified the upstarted by adding . /etc/profile in the line above . /etc/default/zookeeper.  This initializes everything required.  

Sorry, I cant really help much more because company policy forbids it or I would have branched it myself and mad the change.

**Comment by jeffbyrnes** [comment]
Company policy forbids contributing to OSS projects? Good grief…

Thanks for the heads-up on source `/etc/profile`, I’ll see if that helps.

**Comment by DarrenV79** [comment]
One more change I forgot to mention that I solved.  Upstart log also gives

Error: Invalid com.sun.management.jmxremote.port number:

This is because there is no jmx_local attribute in the defaults.  I set this to 4242.

It's more every single change has to be run by legal, which takes time, which they often veto because they are not developers and think its to do with our application.

**Comment by jeffbyrnes** [comment]
Turns out this is quite the rat’s nest, actually. Some things I’ve discovered, diving in to the non-Runit service methods:

* The env vars are all over the place, and are fighting with how ZK itself expects things
* The services do not consistently handle ZooKeeper, or its env vars, and thus have wildly differing settings
* The potential to set an attribute and _not_ get the desired outcome, for any of the three built-in service options, is very high

I’m going to do a much more significant refactor to get this sorted; keep your 👀 on #180.

**Comment by jeffbyrnes** [comment]
@DarrenV79 fixed in v6.0.0

**Comment by DarrenV79** [comment]
Great, will take me a week or so to get around to using it and making the changes I need.  Thanks for doing it so quick.
