### ISSUE TITLE
2.6.0 version error using chef-client 12

### ISSUE THREAD

**Issue by alecventura** [evertrue/zookeeper-cookbook#212]
Hi guys, we currently use 2.6.0 version on our production servers and today I tried to use it, but I had 2 problems:
- poolsaboveground URL is giving me 404.
- and user_resource_abstract_base_class[zookeeper] fails with NotImplementedError

I cloned the repository and fixed the errors by my own, but it would be very nice to have it fixed on your side so we can just use the marketplace recipe as usual. I can provide a pull request tomorrow if you want.

The first error I fixed pointing to apache URL, and the second one I fixed changing providers/default.rb method, inside zk_user_resource definition I used:
- Chef::Resource::User::LinuxUser.new(user, @run_context)
instead of:
- Chef::Resource::User.new(user, @run_context)

I don't know the implications of release a newer version based on 2.6.0 instead of the last 2.* one. We can evaluate the risks/effort of changing for a newer 2.* version if needed.

Please let me know.
Alec

**Comment by jeffbyrnes** [comment]
@alecventura whoa, v2.6.0 is from before I took over maintenance of this cookbook! That’s not even the latest version in the v2.x series, by the way. Here’s what you’re missing that is non-breaking: https://github.com/evertrue/zookeeper-cookbook/compare/v2.6.0...v2.13.1

The old pools aboveground URL was fixed in v3.0.0 (specifically in 302077e3f); it necessitated upgrading to ZK v3.4.7. We went to ZK v3.4.8 in v4.0.0 of this cookbook (specifically f026c3d238). Due to Apache’s lack of adherence to SemVer, I consider any change of the default ZK installed to be potentially breaking.

I’d encourage you to, at the very least, consider upgrading to v4.1.0; that’s the last version of this cookbook before I switched how Java is installed. Here’s a changeset: https://github.com/evertrue/zookeeper-cookbook/compare/v2.6.0...v4.1.0

That said, if you can, I’d encourage you to upgrade to the latest, v10.0.0, if you’re running the latest version of Chef 12 on your systems. The [CHANGELOG](https://github.com/evertrue/zookeeper-cookbook/blob/master/CHANGELOG.md#v260) has details of important changes.

There’ve been quite a lot of fixes and improvements since v2.6.0, and the cookbook installs the latest stable version of ZK, which is a Good Thing™.

If you really wish to stay with the v2.x series, that’s alright, though I don’t recall the `NotImplementedError` you refer to back then. Might be something to do with upgrading the version of Chef you’re using?

**Comment by jeffbyrnes** [comment]
Closing this out as over a year old. Please re-open if you’d like to discuss further!
